"""added added_by field

Revision ID: 52ab52be1400
Revises: 
Create Date: 2023-07-20 12:21:24.519729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ab52be1400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_map', 'original',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_url_map_original'), 'url_map', ['original'], unique=False)
    op.create_unique_constraint(None, 'url_map', ['short'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_map', type_='unique')
    op.drop_index(op.f('ix_url_map_original'), table_name='url_map')
    op.alter_column('url_map', 'short',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('url_map', 'original',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
